### ISSUE TITLE
起動時のリストのDive Noに数値以外が入力できない

### ISSUE THREAD

**Issue by tky129** [clams2017/DiverLog#4]
起動時のリスト画面にて、Dive Noに数値以外を入れると異常終了するため、
No: 1といった表記ができない。

LogListAdapter.java内のsetOnClickListener内の処理にて、
タップされた項目のオブジェクトが保持しているDive No（文字列）を数値へ変換し、そのまま使用している。
そのため、数値以外が入っている場合は正しく文字に変換できずに異常終了する。

**Comment by yoshida-cw** [comment]
divingNumberをArrayList<DiverLog>から取得するよう修正
