### ISSUE TITLE
ログ登録画面でFABが表示されている

### ISSUE THREAD

**Issue by clams2017** [clams2017/DiverLog#5]
# 概要
ログ登録画面でFloatingActionButtonが表示されている。
そのため、ログ登録画面を無限に表示することができてしまう。

# 期待値
ログ登録画面でFloatingActionButtonが表示されていないこと。

# 対応方針検討
* ActivityがFragmentの管理を担い、Callbackでfab表示を切り替える
* ログ登録用のActivityを作成する

**Comment by umamo** [comment]
修正完了したのでクローズ
